### PR TITLE
ci: add codeql action

### PR DESCRIPTION
**Pull request by jackwotherspoon**
Adding [codeql](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql) security scan

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
@hessjcg I think the linter in this repo is too aggressive? Is there a way to not lint the `.github/workflows` folder? It is best practice and more readable to have new lines between stages/steps in workflow yml files. This linter is complaining about it.

**Comment by hessjcg** [comment]
Yeah, lets omit .github/workflows from lint. I'll make a different PR with that change.

**Review by hessjcg — COMMENTED** [review]
LGTM

**Review by hessjcg — APPROVED** [review]
LGTM

**Pull request merged**
