### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by brad-taylor-yvr**
fix sample deployment manifest for test app deployment line 92

Fixes #<issue_number_goes_here> (didn't create an issue)

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by enocom** [comment]
@brad-taylor-yvr Thanks for the PR. If you'd sign the CLA, we can move ahead with it.

**Review by hessjcg — DISMISSED** [review]
Thanks for fixing this!

**Comment by enocom** [comment]
@brad-taylor-yvr friendly ping on this. If you like we can jump in with the same fix.

**Comment by jackwotherspoon** [comment]
@hessjcg @enocom  we can probably make this fix in a separate PR as its been over a month without a response.

**Comment by enocom** [comment]
Replaced by #395.

**Pull request closed without merging**
