### PR TITLE
feat: support sidecar initContainers

### PR DESCRIPTION
**Pull request by ihor-hrytskiv**
This is a proposal to solve the  issue #381. If you approve this design, or if we choose another, I will write tests to cover the code.

> Sidecar containers are a new type of containers that start among the Init containers, run through the lifecycle of the Pod and don’t block pod termination. Kubelet makes a best effort to keep them alive and running while other containers are running.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
Thanks @ihor-hrytskiv for the PR and contribution! 😄 

@hessjcg is OOO this week, but will review this first thing next week when he is back

**Comment by hessjcg** [comment]
Hi, nice work, @ihor-hrytskiv. Thank you for contributing. 

I would like to suggest a bigger change: Instead of creating a new option in the custom resource for sidecar container, the operator should check the Kubernetes API version. The operator always use InitContainer sidecars if they are supported. 

I will going to review the code in more detail over the next few days. I think there may an issue with the logic to maintain the list of ports in use. I'll more review comments soon.

-Jonathan

**Comment by ihor-hrytskiv** [comment]
> Hi, nice work, @ihor-hrytskiv. Thank you for contributing.
> 
> I would like to suggest a bigger change: Instead of creating a new option in the custom resource for sidecar container, the operator should check the Kubernetes API version. The operator always use InitContainer sidecars if they are supported.
> 
> I will review the code in more detail over the next few days. I think there may an issue with the logic to maintain the list of ports in use. I'll more review comments soon.
> 
> -Jonathan

Hi @hessjcg, thanks, I'll try to add this functionality as soon as possible

**Comment by ihor-hrytskiv** [comment]
Hi @hessjcg, take a look please

**Review by hessjcg — COMMENTED** [review]
Nice work. I pushed a commit that updates the integration tests so that they run on the k8s versions 1.28 and latest. I'm going to work on running the end-to-end tests now.

**Comment by jackwotherspoon** [comment]
> Nice work. I pushed a commit that updates the integration tests so that they run on the k8s versions 1.28 and latest. I'm going to work on running the end-to-end tests now.

@hessjcg We no longer run integration tests on forks due to the security issues with the `pull_request_target` GitHub actions trigger we used to use.

So there are two options here:

1. Merge the PR and monitor integrations tests on the continuous build on main closely, revert or send follow up PR to fix tests.
2. Copy the forked branch to your own internal branch and have the tests run on it and then merge this PR and delete your copy branch,

**Comment by hessjcg** [comment]
@jackwotherspoon, Good point. I'm going to run the e2e tests in my dev environment, and if they pass, then I will merge and monitor the e2e tests on main.  I would like to build a way to run e2e tests on PRs again, but that will have to wait.

**Comment by hessjcg** [comment]
E2E tests passed: [E2E Test Github Action](https://github.com/GoogleCloudPlatform/cloud-sql-proxy-operator/actions/runs/11976937777/job/33394014723?pr=629). I'm going to approve and merge this PR.

**Review by hessjcg — APPROVED** [review]

**Comment by jackwotherspoon** [comment]
@utmaks Thanks for raising this! 😄 

Do you mind creating a new issue on this repo so we can get this addressed and fixed. 

Thanks in advance.

**Pull request merged**
